config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  get "/about_me", to: "home#about_me", as: :about_me
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/week.rb
class Week < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cdc_data_controller.rb
class CdcDataController < ApplicationController

  YearStruct = Struct.new(:year, :total, :num_increase, :percent_increase)
  ByCauseStruct = Struct.new(:year, :all, :flu, :heart, :cancer, :cov_multiple, :cov_underlying)

  def index
    years = ["2014", "2015", "2016", "2017", "2018", "2019", "2020"]
    # @totals = {}
    # years.each do |year|
    #   @totals[year] = Week.where(year: year.to_i).sum(:all_cause)
    # end
    # @totals_data = []
    # years.each do |year|
    #   diff = num_diff(year, (year.to_i-1).to_s)
    #   perc_diff = percent_diff(year, (year.to_i - 1).to_s)
    #   @totals_data.push(YearStruct.new(year, @totals[year], diff, perc_diff) )
    # end
    # @by_cause_data = []
    # years.each do |year|
    #   weeks = Week.where(year: year.to_i)
    #   @by_cause_data.push(ByCauseStruct.new(year,
    #                                         weeks.sum(:all_cause),
    #                                         weeks.sum(:influenza_and_pneumonia),
    #                                         weeks.sum(:diseases_of_heart),
    #                                         weeks.sum(:malignant_neoplasms),
    #                                         weeks.sum(:covid_19_multiple_cause_of_death),
    #                                         weeks.sum(:covid_19_underlying_cause_of_death) )
    #                       )
    # end
    @weeks = Week.where(year: 2020).pluck(:week).uniq!.sort!
    @weekly_totals = {"2014" => [],
                      "2015" => [],
                      "2016" => [],
                      "2017" => [],
                      "2018" => [],
                      "2019" => [],
                      "2020" => []}
    years.each do |year|
      @weeks.each do |week|
        @weekly_totals[year] << Week.where(week: week, year: year).sum(:all_cause)
      end
    end
    @weekly_totals
  end

  # returns integer difference of deaths this year vs last
  #
  # @param year [String]
  # @param prev_year [String]
  def num_diff(year, prev_year)
    return 0 if prev_year == "2013"

    @totals[year] - @totals[prev_year]
  end

  # returns % difference between this year and previous year
  #
  # @param year [String]
  # @param prev_year [String]
  # @return [Float]
  def percent_diff(year, prev_year)
    return 0.0 if prev_year == "2013"

    (@totals[year].to_f - @totals[prev_year].to_f) / @totals[prev_year].to_f
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def about_me

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_private, only: [:show, :edit, :update, :destroy, :create]

  # GET /posts
  # GET /posts.json
  def index
    if current_user
      @posts = Post.all.order(created_at: :desc)
    else
      @posts = Post.where(is_public: true).order(created_at: :desc)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def redirect_if_private
      if !current_user
        return redirect_to root_path if !@post.is_public
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :is_public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cdc_data/index.html.erb
<div class="pure-u-2-24">
</div>
<div class="pure-u-20-24">
  <h1>All Deaths per CDC Data</h1>
  <div><small>This data was pulled directly from a CDC dataset that reflects covid-19 deaths and other select causes.  The numbers do not match total deaths exactly but the increase in deaths is still      striking</small></div>
  <div>
    <div id="chartData" data-weeks='<%= @weeks.join(",") %>' 
                        data-weeklyTotals='<%= @weekly_totals.to_json %>'></div>
    <canvas id="lineChart"></canvas>
  </div>
</div>
<%= javascript_pack_tag 'cdc_data' %>

app/views/home/about_me.html.erb
<h1>Hi, I'm Will</h1>

<p>I am a Ruby on Rails developer and I have opinions.  I live in East Tennessee. </p>
<p>At work, I enjoy learning, being challenged, and making things better.</p>
<p>Some other things I enjoy are playing guitar, learning and reading, being outside, and the Wim Hoff Method. </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WillWilson.dev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.5/build/grids-responsive-min.css" />
    <!-- opensource, privacy aware visit tracking -->
    <script data-goatcounter="https://willwilson.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
  </head>

  <body>
    <div class="pure-g">
      <div class="pure-u-1 pure-u-md-1-3"><strong>Will Wilson, Full Stack Developer</strong></div>
      <div class="pure-u-1 pure-u-md-1-3">
        <nav class="pure-menu pure-menu-horizontal pure-menu-open">
          <ul class="pure-menu-list">
            <li><%= link_to "About Me", about_me_path, class: "pure-menu-link" %></li>
            <li><%= link_to "Home", posts_path, class: "pure-menu-link" %></li>
          </ul>
        </nav>
      </div>
    </div>
    <div class="pure-g">
      <div class="pure-u-1 pure-u-md-1-3"></div>
      <div class="pure-u-1 pure-u-md-1-3">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <div class="pure-g">
      <div class="pure-u-1 pure-u-md-6-24">
      </div>
      <div class="pure-u-1 pure-u-md-12-24">
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "pure-form pure-form-stacked")  do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :body %>
    <%= form.rich_text_area :body %>
    :qa
    :qa

    <%= form.label "Public?" %>
    <%= form.check_box :is_public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="pure-u-2-24">
</div>
<div class="pure-u-20-24"

    <h1>Editing Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
  <h1>Posts</h1>
  <% if current_user %>
    <%= link_to "New", new_post_path %>
  <% end %>
  <% @posts.each do |post| %>
    <div>
      <h3><%= link_to post.title, post %></h3>
    </div>
    <div>
      <%= truncate(strip_tags(post.body.to_s), length: 400 ) %>
    </div>

  <% end %>

app/views/posts/new.html.erb
<div class="pure-u-2-24">
</div>
<div class="pure-u-20-24"

    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
  <% if current_user %>
      <%= link_to 'Edit', edit_post_path(@post) %>
  <% end %>
    <%= @post.body %>